### ISSUE TITLE
Auto-play degenerate trip situations

### ISSUE THREAD

**Issue by jl8e** [buttonmen-dev/buttonmen#2638] opened 2020-10-15 18:02 UTC
While they're rare, the small trip vs a large shadow (or worse, a shadow twin) situation is really tedious and unfun when it comes up.

An option to auto-play them would be nice to have.

It's relatively easy to detect: one player has no attacks, and the other has only trip attacks.
The strategy is easy to automate: use biggest trip die to attack the highest-valued die available.
Check if the conditions are still true, and GOTO 10.

(Better yet would be the game engine detecting the condition, and being able to say "you're going to capture this eventually, so you get it", but that is potentially complicated by skills, so not worth doing.)

**Comment by jl8e** [comment] 2020-10-15 18:14
Improved version that allows for the possibility of strategy. (I couldn't think of a situation where it matters, but could be wrong)

When somebody makes a trip attack under the given conditions, repeat the attack until it succeeds or the conditions change.

Also, the existence of this option should be included in the description of the trip skill.

**Comment by irilyth** [comment] 2020-10-15 18:36
This is pretty much a duplicate of #1117.

As I said on that issue, I don't like the idea of fully automating this:

> I think it needs not to be auto, because depending on the result, you might not want to repeat the attack, e.g. if you have two remaining dice, and trip the opposing die such that you don't capture it, but you can now capture it with a Skill Attack with your two dice.

You could implement the full-auto solution for cases where there's only one Trip die and only one Shadow die, but I think implementing some of the ideas from #1117 would be good enough and would cover other cases too.

**Comment by jl8e** [comment] 2020-10-15 18:40
Yeah, I forgot to search for old issues.

But as long as it checks for non-trip attacks each time through, it should work fine.

**Comment by blackshadowshade** [comment] 2020-10-15 22:02
Closing this as a duplicate.

**Closed by blackshadowshade** 2020-10-15 22:02 UTC
Labels: duplicate, enhancement
