### ISSUE TITLE
Preserve Option Dice choices after losing round

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2540] opened 2020-03-12 15:27 UTC
If I am playing with a button with Option Dice and I lose a round I'm asked to set the size of the Option Dice. The default values of the Option Dice are set to their lowest value rather than the most recent value. It might be less confusing (and cause fewer errors) to have the default values be the most recent value.

**Comment by irilyth** [comment] 2020-03-12 15:50
Duplicate of #2148. :^)

**Closed** 2020-03-12 15:49 UTC
