### ISSUE TITLE
Add geographical info to profile

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1737] opened 2015-10-13 20:45 UTC
It'd be nice if user profiles could contain (optional) geographical info. I'd suggest a general free-form "location" field, which people could enter whatever they wanted into ("Europe", "Texas", "Bangalore", "37 Main St", whatever), and also a separate timezone field (to give other players a general guess of when your day and night are). Maybe pre-populate the TZ field with what the user's browser says their timezone is, when they create their account? (If that's a thing that the browser can tell the server.)

**Comment by blackshadowshade** [comment] 2015-10-14 06:07
I'm going to say that this is a duplicate of #1074. Feel free to continue discussion of this there if necessary.

**Closed by blackshadowshade** 2015-10-14 06:07 UTC
Labels: duplicate
