### ISSUE TITLE
Important info missing from top-of-screen action summary

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1667] opened 2015-07-25 01:19 UTC
Sorry, I'm not sure what the proper term is for the header message describing what happened immediately prior to the current turn, and as a result wasn't able to do a good search on whether this issue has already been brought up (I do see that in https://github.com/buttonmen-dev/buttonmen/issues/1072 Chaos referred to is as "the big blob of text at the top", but somehow I don't think that's the common term).

Anyway, in http://dev.buttonweavers.com/ui/game.html?game=1751 at (2015-07-21 21:25:25) I won a round by making a Skill attack and turning some Fire Shadow dice down to values where they couldn't be taken nor take anything else, ending the round and launching the next round, in which I lost initiative, so the screen now told me that it was my opponent's turn. Fair enough.
But that header message indicated none of that, saying only that I had "successfully turned down fire dice", and nothing about the several things that had happened afterwards to bring the game to its current state. And it confused me a lot.

I know all the info was down in the bottom, in "Recent game activity", but I don't usually look there because the header tells me the important stuff. At least, I thought it did. And think it should.

![screen shot 2015-07-21 at 9 26 21 pm](https://cloud.githubusercontent.com/assets/6092544/8887272/bc006cc0-3248-11e5-94f7-3889ca10c390.jpg)

**Comment by blackshadowshade** [comment] 2015-07-25 03:22
Duplicate of #1589.

**Closed** 2015-07-25 03:22 UTC
Labels: duplicate

**Comment by jimmosk** [comment] 2015-07-25 12:48
Doh! Apologies about not finding *my own* previous issue!
