### ISSUE TITLE
Turbo interactions with other skills

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#2156] opened 2017-01-17 03:02 UTC
We've put the initial iteration of turbo up for testing, see #2152.

Bugs and issues about the interaction of turbo with other skills should be listed here for discussion.

**Comment by irilyth** [comment] 2017-01-17 03:18
In http://54.242.94.184/ui/game.html?game=16, I used the Turbo reroll menu to change my (V=6)! from 6 to 12, and got this:

> irilyth performed Power attack using [(V=6)!:4] against [%Ho(2):1]; Defender %Ho(2) was captured; Attacker (V=6)! showing 4 changed to (V=6), which then split into: (V=3) showing 1, and (V=3) showing 1

So Radioactive happened first, and removed Turbo, before my die changed size. Does that seem right, or should Turbo have gone first, changed the size of the die, and then had it split?

I don't remember what the old site used to do. I don't have a good intuition about this at all; maybe it should work similarly to Mood Swing vs Radioactive? I don't remember which way that works either...

**Comment by dwvanstone** [comment] 2017-01-17 16:07
Would it be possible to update RandomBM***Skill so it always includes Turbo as one of its skills? That might be a way to test more interactions.

**Comment by dwvanstone** [comment] 2017-01-17 16:09
http://54.242.94.184/ui/game.html?game=24

"Error from loadGameData: Internal error while loading game."

I had just used a speed turbo die to perform an attack.

**Comment by AdmiralJota** [comment] 2017-01-17 21:25
Another case where it's doing the Turbo size change after the re-roll (instead of before) is in http://54.242.94.184/ui/game.html?game=18 . 

This one is an interesting case because it's happening during a trip attack. Presumably it should be tripping at its new size, not the old one. We might even want to consider adding a specific test case for this particular scenario.

**Comment by AdmiralJota** [comment] 2017-01-17 21:34
Another oddity from that same game:

![turbo](https://cloud.githubusercontent.com/assets/5848173/22040865/9129c114-dcd2-11e6-81c5-64a84bb3fe5b.png)

After the first attack, it looks like the tz(1/30) ended up at 1. But at the start of the second attack, it looks like the same die begins at 30.

**Comment by AdmiralJota** [comment] 2017-01-17 21:36
And, finally, in that same game: tried to turn the tz(1/30) down from 30 to 1 while tripping, and as expected, the game is now in an error state (presumably because the trip reroll happened before the size change).

**Comment by blackshadowshade** [comment] 2017-01-17 21:46
Remember that there's no logging of the turbo change yet, so remember that the log will always be missing the change of size due to turbo.

**Comment by dwvanstone** [comment] 2017-01-18 21:38
http://54.242.94.184/ui/game.html?game=28

If I use a Doppleganger die to capture a Turbo die it gives me this error:

"You attacked with a turbo die but did not specify any turbo die values"

**Comment by blackshadowshade** [comment] 2017-01-18 23:39
Ah, that looks like I need to put in an explicit size set after the doppelganger die changes to a turbo die.

**Comment by blackshadowshade** [comment] 2017-01-19 00:18
Turbo and Time and Space are both present on fnord, mgatten, SailorMur, and Snuff. My gut feeling is that Time and Space should trigger after the Turbo die has been replaced and rolled into the game.

**Comment by irilyth** [comment] 2017-01-19 00:48
I agree that it seems like T&S should trigger when a newly-sized Turbo T&S die enters play, and this seems consistent with how T&S currently triggers when a newly-sized Mighty or Weak T&S die enters play.

**Comment by AdmiralJota** [comment] 2017-01-19 18:29
How about Berserk? In game http://54.242.94.184/ui/game.html?game=28, I just used a B(1/30=1)! to do a Berserk attack, changing it to 30 in the process. From the results, it looks like the Berserk splitting happened first, and then the Turbo completely overrode it.

The game log description was:

> Jota performed Berserk attack using [B(1/30=1)!:1] against [tD(4):1]; Defender tD(4) was captured; Attacker B(1/30=1)! recipe changed from B(1/30=1)! to (1/30=1)!, rerolled 1 => 1

And the die is now listed on the play mat as "(1/30=30)!". 

Is this how we want it to behave? 

It seems to me that it would be more interesting/logical/intuitive if either A) Turbo happened first, and then Berserk split whatever the new size was (so that the effective range of a B(X)! after a Berserk attack became 2-10 instead of 4-20) or B) when a Berserk die "is replaced with a non-berserk die with half the number of sides it previously had", the Turbo (and possibly even the fact that it was an X swing) were both considered a part of the *old* die size, and were both lost when Berserk replaced it.

How do we presently handle Berserk Mood dice?

Also, as a side note, we might want to make the game log more informative when we're handling size/recipe changes, to let the player know what caused that particular change. It's normally fairly clear, but when there are multiple size-changing skills potentially in play, it might be nice to know which change was from which.

**Comment by AdmiralJota** [comment] 2017-01-19 18:58
Here's an interesting one: Doppelganger:

![turbo2](https://cloud.githubusercontent.com/assets/5848173/22120687/d57c4698-de4e-11e6-9e35-1ba26d457686.png)

I'm trying to capture a Turbo die with a Doppelganger die, but it's not letting me. Presumably because Doppelganger will turn my die *into* a Turbo die, and Turbo must be trying to trigger after that happens. My guess at the correct behavior is that Turbo should probably trigger *before* Doppelganger does, so that by the time it's doppeled, it's already past that stage.

**Comment by dwvanstone** [comment] 2017-01-19 19:05
I've ruined that game by taking a die with a (1/30=30)! and resizing it to a 1-sided die...now it's in an internal error state.   http://54.242.94.184/ui/game.html?game=28

**Comment by blackshadowshade** [comment] 2017-01-20 00:32
Jota, devious already noted that bug with Doppelganger a day ago. :)

**Comment by blackshadowshade** [comment] 2017-01-20 00:34
So, just FYI, I'll be working on the following fixes to Turbo this weekend:
- causing Turbo dice to reroll after the new size has been applied
- setting the size of Turbo dice after they've been created via Doppelganger
- adding basic logging of the change in die size after Turbo, which should also show the new value

**Comment by AdmiralJota** [comment] 2017-01-20 01:28
> Jota, devious already noted that bug with Doppelganger a day ago. :)

Then I demand that you add some *new* bugs for us to find!

**Comment by blackshadowshade** [comment] 2017-01-20 01:43
I'm working on it!  XD

**Comment by blackshadowshade** [comment] 2017-01-25 00:16
To keep you all in the loop, I thought I had addressed the first point, but the responder tests told me that I would need to consider the case of Trip Turbo dice performing trip attacks as a special case.

In my interpretation of Turbo dice performing a trip attack, the die size changes before the trip attack is performed, so there is still only a single roll of the attacking die in this case. To accommodate this, I've had to add an extra game state to allow the selection of the die size before the trip attack occurs, and that's what I'm currently working on.

**Comment by AdmiralJota** [comment] 2017-01-25 04:04
Is that an extra state in the UI or just an extra stage that the backend goes through while resolving the attack?

**Comment by blackshadowshade** [comment] 2017-01-25 04:08
Because we are doing the turbo resize choice simultaneous with the choice of attack, the UI doesn't need to know about this new game state. The interface level then passes the turbo size choice both before *and* after the COMMIT_ATTACK game state, and the backend decides whether it needs that information.

**Comment by blackshadowshade** [comment] 2017-02-01 16:08
Okay, I've now got turbo interacting sensibly with trip, and logging is fully functional.

Now I can get back to fixing the interaction between turbo and doppelganger!

**Comment by blackshadowshade** [comment] 2017-02-04 04:47
Right, I've now got turbo and doppelganger working together. Onto the UI changes!

**Comment by blackshadowshade** [comment] 2017-02-08 00:18
So, in #2152, Jota noted that NoopMan has a chance turbo die. In fact, Jenniegirl also has one.

The question here is whether the chance reroll should trigger the turbo skill.

Jota's parallel to Mood Chance doesn't work, because there are no current recipes with both mood and chance on the one die.

**Comment by blackshadowshade** [comment] 2017-02-08 00:28
irilyth has expressed a preference to change the wording of the Turbo skill so that it explicitly triggers on an attack.

I think we should approach this issue on two fronts: pragmatism and idealism. The first says that there's only one playable button (Jenniegirl has some odd skill that I don't recognise on the last die), and it's a Fanatic anyway, and it's going to be a lot of development effort to get it working. The second says that the combination of chance and turbo might actually be quite a powerful and interesting synergy.

Either way, pragmatism will win out in the short term. However, I'm open to pursuing turbo resize at the chance reroll eventually if people think it's worth doing.

**Comment by irilyth** [comment] 2017-02-08 00:39
> irilyth has expressed a preference to change the wording of the Turbo skill so that it explicitly triggers on an attack.

If we don't do this, then Ornery Turbo dice should be allowed to change size whenever they re-roll due to Ornery.

I think we should change the wording primarily for idealistic reasons: Turbo is already incredibly overpowered, so it seems to me the wrong approach to make it even *more* powerful when combined with other skills.

Jenniegirl's rightmost die is cor@(X)!, i.e. Reserve Chance Ornery Chaotic Turbo X Swing.

**Comment by AdmiralJota** [comment] 2017-02-08 01:08
> If we don't do this, then Ornery Turbo dice should be allowed to change size whenever they re-roll due to Ornery.

Not necessarily. IMO, we could pretty reasonably interpret "...every time you roll it" for Turbo dice as referring to the player intentionally choosing to roll the die, and "Ornery dice reroll..." as referring to the dice spontaneously rerolling on their own.

But that said, I am fine with following pragmatics in this case. (So long as we verify that we're keeping consistency with any future c? dice that might be added on future buttons.)

**Comment by irilyth** [comment] 2017-02-08 01:18
Sure, we could rewrite it as "choose to roll", which would let you Turbo with Chance, but not with Ornery, or when the target of a Boom or Trip Attack.

I don't think it's particularly important that Mood and Turbo be identical in this respect. An Ornery Mood Swing die changes size, for example, and I think it should, but I don't think Ornery Turbo should. A Mood Swing die that's the target of a Trip Attack or a Boom Attack changes size, and I think it should, but I don't think a Turbo die should in those circumstances.

**Comment by irilyth** [comment] 2017-02-08 01:21
One question about the "choose to roll" thing: If there was a skill that forced the other player to use a particular die on their next attack (which there might be, I can't remember; but there could be), you could argue that you then didn't "choose" to attack with that die; but if it was Turbo, I think you could reasonably argue that you should be allowed to change its size.

I like "when you use it in an attack" best.

**Comment by AdmiralJota** [comment] 2017-02-08 01:27
> An Ornery Mood Swing die changes size, for example, and I think it should, but I don't think Ornery Turbo should. A Mood Swing die that's the target of a Trip Attack or a Boom Attack changes size, and I think it should, but I don't think a Turbo die should in those circumstances.

That's fair enough.

> One question about the "choose to roll" thing: If there was a skill that forced the other player to use a particular die on their next attack (which there might be, I can't remember; but there could be), you could argue that you then didn't "choose" to attack with that die; but if it was Turbo, I think you could reasonably argue that you should be allowed to change its size.

I think this part is a little bit silly, though: you were the one who suggested changing the wording of the skill to say "choose to roll". I was only suggesting that we might interpret the existing wording in what seemed like a reasonable way (to refer to active rolls rather than passive ones).

**Comment by irilyth** [comment] 2017-02-08 02:43
> I think this part is a little bit silly, though: you were the one who suggested changing the wording of the skill to say "choose to roll".

Enh, sure; I was figuring that "we could interpret this ambiguous comment this way" would also including rewriting it to make it clearer, but perhaps that's not what you had in mind. :^)

**Comment by blackshadowshade** [comment] 2017-02-08 06:37
So, any concrete suggestions for the complete wording of the description of Turbo, including skill interactions?

**Comment by blackshadowshade** [comment] 2017-02-08 06:39
For interest, the current description is:

After your starting roll, you may change the size of a Turbo Swing or Option die every time you roll it. Decide on a size first that is valid for the Swing or Option type, then roll the new die as usual.

And it has the following two interactions:

Boom => If a Turbo Die is rerolled because it is the target of a Boom attack, then the size cannot be changed.

Trip => If a Turbo Die is rerolled because it is the target of a Trip attack, then the size cannot be changed.

**Comment by dwvanstone** [comment] 2017-02-08 17:16
First of all, thank you all for working on Turbo. It's an exciting skill that will make the website even more fun when it goes live!

We could abandon resizing on a chance reroll [not a big gain to include that] and make the description simply:

"...you may change the size of a Turbo Swing or Option die every time you roll it as part of your attack"

I think you could then remove the special interactions.

**Comment by blackshadowshade** [comment] 2017-02-08 21:08
And what about Socrates?

**Comment by AdmiralJota** [comment] 2017-02-08 21:19
...do we support Socrates yet?

**Comment by blackshadowshade** [comment] 2017-02-08 21:20
It's on the horizon, since Socrates is my favourite button.

**Comment by irilyth** [comment] 2017-02-08 21:22
Not sure what I think should happen with Socrates. I bet the old site didn't let it change size, but that might have been pragmatic.

I think it'd be fine to go either way; if you don't want Socrates to be able to modify the opponent's Turbo die size, phrase it as "you may change the size of your Turbo Swing or Option die". Socrates is using my die; the die is still mine, so Socrates can't change it.

But I think letting Socrates change it would be ok too.

**Comment by blackshadowshade** [comment] 2017-02-08 21:23
The original wording for Turbo expressly says that you can only change the size of your own Turbo die.

**Comment by dwvanstone** [comment] 2017-02-08 21:23
Remind me...if you use Socrates and capture my die using another die of mine...do I even reroll the one that was used?

**Comment by blackshadowshade** [comment] 2017-02-08 21:23
Yes, it gets rerolled.

**Comment by dwvanstone** [comment] 2017-02-08 21:26
The question to me is whether the owner of the turbo die gets to change the size after the opponent uses a Socrates attack. I'd suggest no (to simplify the interface).

**Comment by blackshadowshade** [comment] 2017-02-08 21:27
I think not, because it's not the owner that is rolling the die.

**Comment by irilyth** [comment] 2017-02-08 21:30
I agree, either Socrates gets to change it or no one does; definitely not the owner. (And if the Turbo description mentions "owner", then great. Well, too bad for Socrates, but I think that settles the question unless we want to change that wording.)

**Comment by blackshadowshade** [comment] 2017-02-08 21:33
So, this?

"...you may change the size of your own Turbo Swing or Option die every time you roll it as part of your attack"

**Comment by dwvanstone** [comment] 2017-02-08 21:34
Sure!

**Comment by irilyth** [comment] 2017-02-09 03:27
Hmm: I'm not sure about IIconfused's `d(Y=2)! die. I can't remember if you could resize it on the turn you brought it into play on the old site; and in general, the skills on Warrior dice don't work until they come into player, like a Stinger Warrior die cant' be used as anything from 1 - N because Stinger doesn't work while Warrior is active.

I don't have a strong feeling about it in this case -- maybe it shouldn't work, because you're using the Turbo skill before the die ever enters play; or maybe it should, because the die is in play after you've attacked with it, so you can Turbo it before you roll it -- but it might be an interaction worth mentioning, whichever way we decide to go with it.

Are there any other size-changing Warrior dice? I don't see any at a glance, although there are a couple of other buttons with Warrior Turbo Swing dice.

**Comment by dwvanstone** [comment] 2017-02-09 15:07
I'd say you would set the Y value as usual at the beginning of the round, the die is set to the max value, but when you use it as a warrior die as part of an attack you can change the size for its reroll. As you say, the die is in play after you've attacked with it and you resize it after the attack (even though the UI looks like you're setting it during the attack).

I didn't see any other size-changing Warrior dice beyond the turbo swing dice. We did talk about having a zombie button with lots of `m(0) dice at one point. (or maybe they were `mp(0))

**Comment by dwvanstone** [comment] 2017-02-16 19:55
Kaori & I are playing a nelde v. nelde game on the dev site. We both picked Y=1...and I think we're in an endless loop. Neither of us can take the other dice, we can't trip anything, there's nothing we can do. I think in the old site if five games in a row were tied both players were allowed to pick new swing values. (I couldn't find this as an existing issue - if it's not one I'll create it.)

I was thinking this is a reason not to release nelde, but I suppose it's no worse than playing a Dead Guy v. Dead Guy game. At least the games go by faster!

**Comment by irilyth** [comment] 2017-02-16 20:00
#1394 is the ticket to allow swing die changes after three ties in a row.

**Comment by dwvanstone** [comment] 2017-02-16 20:04
Three, five, ...yeah, three is probably better. Thanks for finding the ticket!

**Comment by blackshadowshade** [comment] 2017-02-16 22:04
Just checking: the game allows you to pass, right?

**Comment by dwvanstone** [comment] 2017-02-17 18:30
My choices are Pass and SURRENDER!?   So that part is working fine!

**Comment by cgolubi1** [comment] 2017-04-03 13:18
Okay, here's a nice philosophical question for everyone.

For reasons passing human comprehension you are playing bobby 5150.  Your only remaining die is `t(1/30)!`, which is currently 1-sided.  Your opponent has only shadow twin dice.  Are you *obligated* to turbo up to 30 sides so that you can trip attack your opponent?  Or should you be allowed to pass?

(Right now, the implementation would obligate you to turbo up.  But what should it be?)

**Comment by dwvanstone** [comment] 2017-04-03 14:46
It seems that PASS is only an option if you have no legal move. (Because of poison dice, I suppose.) You do have a legal move in this case, so I think you are obligated to turbo up.

**Comment by irilyth** [comment] 2017-04-03 15:09
Warrior dice are an exception to this: You aren't obliged to use Warrior if you don't want to, and can pass if you have no legal move without Warrior.

Some arguments:

- Turbo should work like Warrior in this respect: The Warrior die isn't in play unless you use the Warrior skill to bring it into play; the Turbo die has no legal attack unless you use the Turbo skill to make it larger.

- The Turbo die *is* in play, so it's legit for the rules to consider its Turbo-ness, just like it's legit for the rules to consider the possibility that a Trip Mood Swing Die will change size. Also, Turbo is already plenty powerful, making it even more powerful in this way is not advantageous from a gameplay perspective.

I'm inclined towards the latter, especially since Warrior very explicitly mentions that they're an exception; I don't think there's a general precedent for "the rules for passing shouldn't consider dice that might change if you use them". If we do go that way, it might be worth mentioning it as an interaction, just so folks understand that it's a deliberate decision and not a bug. :^)

**Comment by AdmiralJota** [comment] 2017-04-03 23:47
I would say that *if* Turbo only triggered after the attack completed (like with most attacks), then I'd probably consider it a separate thing and treat it like Warrior. But since Turbo-resizing is an intrinsic part of performing a Trip attack, I don't think I can really justify that point of view. I say no passing then, alas.

**Closed** 2017-04-28 11:38 UTC
Labels: backend, bug
