### ISSUE TITLE
Stay logged in even when browser closes and reopens

### ISSUE THREAD

**Issue by blackshadowshade** [buttonmen-dev/buttonmen#1745] opened 2015-10-27 00:55 UTC
It would be nice for the browser to remain logged in even when it is closed and reopened, so that users don't need to log in each time.

**Comment by danlangford** [comment] 2015-10-27 02:37
What is the php session timeout on the tokens in the DB?

**Comment by blackshadowshade** [comment] 2015-10-27 03:44
At https://github.com/buttonmen-dev/buttonmen/blob/master/src/api/api_core.php, lines 58 and 59, we have the following lines:

    setcookie('auth_userid', $result['id'], 0, '/', '', FALSE);
    setcookie('auth_key', $auth_key, 0, '/', '', FALSE);

Here, we're setting the expiry of the cookie to zero, which means that the cookies expire at the end of the session.

I guess that we need to find an appropriate value here instead of zero. Anyone with any preferences?

**Comment by yawetag** [comment] 2015-10-27 05:41
First off, can multiple cookies be used for the same login? If I'm logging
in from home, work, iPad, and mobile, I don't want to have to login at each
device every time because the last login erased the others.

Once that's solved, I don't see why the cookie can't be permanent. We're
not a top-secret agency that needs dual-password logins and, except for a
very minor few of us, don't really have to worry about someone taking turns
for us.

One other thought is that ALL cookies assigned to a login should be reset
when the password is changed. This way, you're forcing all the devices to
re-login when a password is changed. This will prevent a hacked account
(again, it's going to be very rare) from continuing to be used after the
correct user resets their credentials.


Andrew Senger
asenger@gmail.com

**Comment by blackshadowshade** [comment] 2015-10-27 06:00
There's a comment in the file at line 37 that says

    // if the user has too many active logins (allow 6), delete the oldest

which implies to me that we support up to 6 active logins. This should be easily testable by our testers.


For the password change issue, I presume that all we need to do is delete all the authorisation keys in the database and then add the authorisation key corresponding to the session that is changing the password.

**Comment by blackshadowshade** [comment] 2015-10-27 06:17
http://stackoverflow.com/questions/3290424/set-a-cookie-to-never-expire

This notes that PHP setcookie has a 32-bit issue that needs to be considered.

**Comment by yawetag** [comment] 2015-10-27 14:54
I think 6 is reasonable. I'm on two, but don't use my mobile or ipad on the
site. If you're carrying around more than 6 devices you use frequently, I'm
envious.


Andrew Senger
asenger@gmail.com

**Comment by irilyth** [comment] 2015-10-27 15:04
FWIW, I've noticed lately that I seem to be getting logged out more often than I used to; but I don't have a very good timeframe for that, and I upgrade my browser on both laptop and phone whenever there's a security update, so it could be any number of factors. Anecdotally, it seems like almost any time I log in from one, I have to log back in from the other when I switch back, but I can't reproduce that by just switching back and forth. When I log out from one by clicking the Logout button, the other stays logged in, which seems good.

For me personally, my browser remembers my password, so if I do get logged out, it's exactly one extra click, so I barely even notice.

**Closed** 2016-07-10 12:53 UTC
Labels: enhancement, fix submitted
