### ISSUE TITLE
Morphing Trip dice

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#802] opened 2014-04-22 16:15 UTC
Do Morphing Trip dice morph before they trip? They should, since otherwise they might roll a number higher than their range (e.g. if a tm(20) trips a (4), rolls a 9, and then morphs to 4).

(This came up in chat in a game, and we wanted to check; we can't test it since no currently-playable buttons have the combination.)

**Comment by edpegg** [comment] 2015-02-12 23:32
In the current skill_order_array , Konstant is listed twice.

https://github.com/buttonmen-dev/buttonmen/blob/master/src/engine/BMSkill.php:
protected static function skill_order_array() {

**Comment by blackshadowshade** [comment] 2015-02-13 00:00
So is morphing. Apparently, that was a merge gone bad. Let me take a look at what was intended.

**Comment by blackshadowshade** [comment] 2015-02-13 00:05
Also, Fire seems to be missing from being explicitly listed.

**Comment by blackshadowshade** [comment] 2015-02-13 00:36
Closing this, and shifting the bug to #1526.

**Closed by blackshadowshade** 2015-02-13 00:36 UTC
Labels: backend, bug
