### ISSUE TITLE
Remove forced linebreak from games list headers on Overview page

### ISSUE THREAD

**Issue by AdmiralJota** [buttonmen-dev/buttonmen#1902] opened 2016-01-06 13:26 UTC
There's a "<br>" being inserted into the "Score W/L/T (Max)" header on the Overview page. I think this is leftover from when we were adding the Description column, before we had decided to truncate that field to save horizontal space.

In any case, I'm pretty sure it's no longer necessary, and it makes the header line two rows when it doesn't need to be, so I think we should tidy up and remove it.

**Comment by AdmiralJota** [comment] 2016-01-06 13:28
https://gist.github.com/AdmiralJota/c39b379de1937b37c829

**Comment by cgolubi1** [comment] 2016-01-06 13:39
I believe it is needed, and would be super grateful if anyone had time to go through the issue history and find the explanation of why.  If no one does, i'll look for it when i have time.

**Comment by cgolubi1** [comment] 2016-01-06 13:41
(Removed fix submitted because i think that's just for a PR submitted.  If you and shadowshade negotiated something different, though, readd it, whatever is fine.)

**Comment by AdmiralJota** [comment] 2016-01-06 14:36
It looks like the forced line breaks for "Your Button", "Opponent's Button" and "Score W/L/T (Max)" were added in https://github.com/buttonmen-dev/buttonmen/commit/9254ef524e994a3421c9aeae10aef82f86ce84ab. The breaks for the first two were removed in https://github.com/buttonmen-dev/buttonmen/commit/0766737caa6c1cef985f1ea1d3a97d1cee92a4b1.

The latter was a part of pull request #1815. The only thing I see in there (or in the issues that it resolves) that are specifically about wrapping in that column is a comment from you where you ask that @blackshadowshade remove a span that forcibly *prevented* wrapping (and he did remove that). So I'm guessing that might be what you're thinking of. 

I don't think the question of whether or not that break should be retained was ever brought up. I strongly suspect that it would have been removed in https://github.com/buttonmen-dev/buttonmen/commit/0766737caa6c1cef985f1ea1d3a97d1cee92a4b1 along with the others, but was simply missed because it had the additional span wrapping part of it.

**Comment by cgolubi1** [comment] 2016-01-06 15:03
I believe the proposed change breaks my personal browser experience on the overview page.  With the change, my browser does *not* voluntarily wrap the header, and i get a horizontal scrollbar; without the change i don't.  I understand that this change is important to Jota, and the next time i do testing i will prioritize taking some screencaps to confirm or deny that this is a problem for me.

Chaos

**Comment by irilyth** [comment] 2016-01-06 15:24
One other note is that the column header now is *already* wider than the data in the column. Making the header even wider is going to make the whole table look funny, as all the data in that column will have a bunch of whitespace on either side of it.

I think leaving it as-is is fine; another option would be to remove the word "Score" entirely, if we think that "W/L/T (Max)" is sufficient to explain what that column is. (I think it's sufficient, myself.)

**Comment by AdmiralJota** [comment] 2016-01-06 15:35
I'd be fine with removing the word "Score".

**Comment by blackshadowshade** [comment] 2016-01-06 19:18
@AdmiralJota, the label that I made for your gist fixes is the "fix suggested" label, not the "fix submitted" label. Sorry for any misunderstanding.

**Comment by blackshadowshade** [comment] 2016-01-06 19:25
I can't find the issue at the moment, but I remember that Chaos explicitly made screenshots in the appropriate issue showing that with her screen/browser, that the overview tables become too wide.

**Comment by AdmiralJota** [comment] 2016-01-06 19:57
> @AdmiralJota, the label that I made for your gist fixes is the "fix suggested" label, not the "fix submitted" label. Sorry for any misunderstanding.

Thanks, my bad.

I've updated my gist with irilyth's suggestion of removing the word "Score", since I think that would solve everyone's problems: https://gist.github.com/AdmiralJota/c39b379de1937b37c829

**Comment by blackshadowshade** [comment] 2016-01-06 20:42
I wonder if removing the Score line is acceptable. For old hands who've had it there forever, sure, it's obvious what that column is, but I wonder how obvious it would be to a new player, especially without any sort of help text (mouseover or on click). I *guess* that it might be enough to put the meaning of W/L/T in the help documentation---I don't know if it's obvious to someone whose first language isn't English.

**Comment by AdmiralJota** [comment] 2016-01-06 20:56
Is this a question we should bring to the forums, to get broader feedback?

**Comment by blackshadowshade** [comment] 2016-01-06 21:20
Just for information, I've found the issue where Chaos brought up the problem with wrapping: #1768. Here, if we didn't include any hard line breaks, Firefox decided to do aggressive line breaking, forcing three lines instead of two.

**Comment by cgolubi1** [comment] 2016-01-06 21:27
On Wed, 06 Jan, 2016 at 13:20:02 -0800, James Ong wrote:

> Just for information, I've found the issue where Chaos brought up the problem with wrapping: #1768. Here, if we didn't include any hard line breaks, Firefox decided to do aggressive line breaking, forcing three lines instead of two.

That's not the impact i'm concerned about.  I will verify the impact i'm having and report on it in a couple of days.  I apologize for holding things up, but my request is that you please let me hold things up until i can actually report on what the actual problem this change will cause me is or isn't.

Chaos

**Comment by irilyth** [comment] 2016-01-06 21:52
I tried it, and it doesn't actually make the table wider than my browser's usual window, but it does (IMHO) look fairly silly to have the column so much wider than the data in the column.

I think any of (a) let the header continue to be two lines tall; (b) drop the word "Score" (optionally adding hovertext or a link to explain what the W/L/T business means); (c) drop the "W/L/T" part (optionally adding hovertext or a link to explain etc); would be better than having "Score W/L/T (Max)" all on one line.

Here's a screenshot from my browser; as you can see, it makes the Score column become the second widest, despite the data in the column being the narrowest (or maybe second narrowest).

![bm](https://cloud.githubusercontent.com/assets/4923138/12155870/a458b13e-b495-11e5-9917-4272e08e8a79.png)

**Comment by AdmiralJota** [comment] 2016-01-06 23:11
That screenshot looks 100% better!

**Comment by cgolubi1** [comment] 2016-01-07 01:15
Huh, okay, so actually i'm wrong.  If you just do:
```diff
diff --git a/src/ui/js/Overview.js b/src/ui/js/Overview.js
index 564a6ac..0ee6661 100644
--- a/src/ui/js/Overview.js
+++ b/src/ui/js/Overview.js
@@ -291,9 +291,7 @@ Overview.addTableStructure = function(tableClass, sectionHeader, showDismiss) {
     headerRow.append($('<th>', {'html': 'Your Button', }));
     headerRow.append($('<th>', {'html': 'Opponent\'s Button', }));
     headerRow.append($('<th>', {'text': 'Opponent', }));
-    headerRow.append( $('<th>', {'html':
-      'Score<br/>W/L/T (Max)',
-    }));
+    headerRow.append($('<th>', {'html': 'Score W/L/T (Max)', }));
     headerRow.append($('<th>', {'text': 'Description', }));
     headerRow.append($('<th>', {'text': 'Inactivity', }));
     if (showDismiss) {
```
i.e. replace the `<br/>` with a normal space, then my browser does exactly the same thing it's doing now, displaying the header on three lines (see screencap below).

The thing that was causing the problem for me was something we were trying at one point which *prevented* the header from wrapping --- i wonder if it was using an `&nbsp;` instead of a space --- and that was forcing my display to have a horizontal scrollbar.

So, anyway, i have no problem with removing the `<br/>` and replacing it with a normal space, because it appears to make no difference whatsoever to me, so if it makes people with wide browsers happy, more power.

![my_current_overview](https://cloud.githubusercontent.com/assets/2898207/12159641/078a7906-b4b2-11e5-9d3f-793b07092db1.png)

**Comment by cgolubi1** [comment] 2016-01-07 01:16
(I don't have an opinion about the all-important question of whether the word "Score" is important or not.  I can try to fake one if really required, but in actual fact i don't feel strongly either way.)

**Comment by blackshadowshade** [comment] 2016-02-16 03:30
So, I'm inclined to argue for leaving the line break there. Before adding the line break, we instead had "Score (W/L/T (Max))", which I thought looked awkward. I removed the second pair of brackets and added the line break to separate the "Score" part from the "W/L/T (Max)" part.

I think that both the "Score" and "W/L/T (Max)" parts convey important distinct pieces of information, so I think that both should be there, but distinctly separated.

**Comment by jimmosk** [comment] 2016-02-22 04:17
I don't know whether this is related to changes that have been made in response to this issue; if it isn't let me know and I can start a separate thread, but recently the Overview page just got a lot less dense because 5-digit game number aren't fitting on a single line, yuk:

![screen shot 2016-02-21 at 11 12 58 pm](https://cloud.githubusercontent.com/assets/6092544/13209398/54dbe4a2-d8f1-11e5-9bd6-4861757707be.jpg)

**Comment by blackshadowshade** [comment] 2016-02-22 04:21
Yeah, it's not directly related to anything on this issue. I've noticed the difference caused by 5-digit game numbers also, and I'm wondering whether we need to do something with the default font sizes.

**Comment by jimmosk** [comment] 2016-02-22 05:39
All right, I'll start a separate issue!

**Comment by blackshadowshade** [comment] 2016-02-22 14:16
I'm labelling this one as wontfix and closing it.

**Closed by blackshadowshade** 2016-02-22 14:16 UTC
Labels: enhancement, fix suggested, UI, wontfix
