### ISSUE TITLE
Option dice representation on game page is cluttered

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#822] opened 2014-05-03 03:17 UTC
On the game page, in the section where you're selecting dice to attack with (or against), representing Option dice as things like "(1/8=1)" seems to me to be cluttered and confusing. I guess it's consistent with the "(X=17)" phrasing for swing dice, but I'm not all that fond of that either. Why not just put the size there? The fact that it's an Option die generally isn't relevant during the game, and if you need to know, the recipe is right there under the button.

(How did the old site do this? Ah, it spelled out the whole thing like "Option 4/10 (with 10 sides)", hmm.)

**Comment by irilyth** [comment] 2015-08-26 20:30
I got bitten by this again just now, mistakenly reading a (4/20=20) as a four-sider rather than a 20-sider, because the thing immediately after the opening parens is a 4. I don't have a current proposal for this, but wanted to bump that I'm thinking about it.

(A half-assed proposal: What about something Javascripty that only displayed the current size, including for swing dice, but with a color and/or adjecent symbol (like an asterisk) indicating that there was more going on than a regular die of that size, which you could hover over and/or click on to get more details?)

**Comment by blackshadowshade** [comment] 2015-09-01 01:52
What about using font size or bolding the appropriate part of the option representation?

**Comment by irilyth** [comment] 2016-04-04 02:52
I made a quick mockup of bolding, and I think it's better than it is now, but the current display still just seems terrible to me, full of irrelevant and confusing information. Like, the thing where S swing dice look like Shadow dice, and Z swing dice like Speed dice, which I guess is beyond the scope of this ticket; #216 seems to have been somewhat about the more general issue, but that's been closed for ages, so probably no one wants to revisit that.

Here's what bold looks like, anyway.

![bm](https://cloud.githubusercontent.com/assets/4923138/14237205/a6e8f9b0-f9ee-11e5-8a5c-f1d660274e77.png)

**Comment by blackshadowshade** [comment] 2016-04-04 05:27
Just letting people know that irilyth is contemplating having this for his BotM. I've told him that I'd like for there to be some consensus before I'll spend any time programming this, so pipe up now if you have an opinion about how option dice (and perhaps swing dice) are displayed.

**Comment by dwvanstone** [comment] 2016-04-04 12:52
Could you send in a screenshot with the confusion between S dice and shadow dice or a Z dice and speed dice?

**Comment by AdmiralJota** [comment] 2016-04-04 14:53
Is the bolding the only change that you've made so far? If so, it looks fine to me.

Another option might be to have the "blah =" in a smaller font, or perhaps a lighter shade, to make it less pronounced. (Possibly in addition to the bolding the actual size.)

**Comment by irilyth** [comment] 2016-04-13 12:59
Whoops, I meant to actually BFOTM this, but forgot. Did now.

> Could you send in a screenshot with the confusion between S dice and shadow dice or a Z dice and speed dice?

I don't really have a screenshot of this; all I mean is that since the S and the Z from Swing dice look a lot like the s and z from Shadow and Speed dice, I sometimes mistake a Z swing die for a Speed die.

> Is the bolding the only change that you've made so far? If so, it looks fine to me.

Yep, that's all I did in that mockup.

> Another option might be to have the "blah =" in a smaller font, or perhaps a lighter shade, to make it less pronounced. (Possibly in addition to the bolding the actual size.)

Yeah, making it gray might help more. Here's a screenshot of that:

![bm](https://cloud.githubusercontent.com/assets/4923138/14493892/faba3680-0155-11e6-8f6a-3a92abb1642e.png)

I think it's better, although it looks a little oddly imbalanced. But part of that is because the information being displayed is an odd imbalance of important and irrelevant. :^)

**Comment by dwvanstone** [comment] 2016-04-13 15:49
The information (X=) and (3/12=) are only really relevant once the game is over, or if the buttons were also mad/mood/turbo. In your example, (3/12=3) is simply a 3-sided die during the entire game. There already is a mouse-over information saying what a button is. Why not just leave off the irrelevant information? What's the argument for keeping it on the screen?

For an X mood button with 4 sides, how about (4)X? (I.e., the "X" only shows up to indicate the type of mood dice it is.) For Z turbo with 12 sides you could have (12)Z!  For Option turbo 1/30 die with only 1 side you could have (1)1/30! The part in parentheses is always the current size of the die, things to the left of the parentheses are the powers of the day, the things to the right are for mood/mad/turbo.

**Comment by AdmiralJota** [comment] 2016-04-13 15:55
I think that screenshot looks pretty reasonable.

> The information (X=) and (3/12=) are only really relevant once the game is over, or if the buttons were also mad/mood/turbo.

It's relevant if you care about how your decisions are related to what's going on and what you might do about them in the future. E.g., noticing that the reason you're losing is because you set your X swing too small to be able to use it to capture your opponent's dice would be much harder if it weren't labelled as an X swing.

Not to mention that it's just nice to have it there.

**Comment by irilyth** [comment] 2016-04-13 16:03
The full recipe is right there under the button, though, so if you feel like your side count is causing you problems, it's not hard to look over there and see what your options for next round are. An even then, it's a decision for what you might do next round, when you'll be asked to set your Swing/Option dice anyway, so it's not like you're going to forget at that point.

I don't think it's "just nice to have it there"; I think it's distracting and confusing. I think we obviously disagree about this, which is fine. :^)

(My other go-to solution would be "how about a user preference!" but it seems like user preferences, at least for in-game things, tend to make testing a lot harder, so I've stopped suggesting that. But that seems like an obvious solution here, given that different people will want different information, from the current some-information view, to the very dense view I'm interested in, to the very verbose view that the old site used to have.)

**Comment by AdmiralJota** [comment] 2016-04-13 16:11
I dunno; I thought the bold and grey option seemed like a really good compromise.

**Comment by Hurtay** [comment] 2016-04-13 16:21
I have to admit I don't like the grey at all. It's confusing to work with different colours within the recipe. And it's hard to read anyway. 
Bold is nice. 
Leave it out completely is nice, too. I'd agree that's even better.
If you want to leave it in but have it less prominent maybe a smaller font is an option? Maybe not.
This mix of bold/normal and black/grey and left/right/in/out of () is hard to understand, not only for newbies.

**Comment by blackshadowshade** [comment] 2016-04-13 17:55
My personal view on this is that the die recipe is important. If I consistently lose my (X=20) die early, then this is important to know, more so than "I lost a 20-sider, oh wait, let me check the button recipe, yeah, it was a swing die which I could have set differently".

Also, if we change the representation, we'll quite probably need to change the logging to match, otherwise this will prove to be confusing.

I'm not trying to pour water on the idea, but I think that whatever enhancement gets decided here needs to be some or all of:
- consistent
- not confusing
- not distracting
- helpful
- customisable (?), depending on play style/level

**Comment by blackshadowshade** [comment] 2016-04-13 17:57
One other suggestion: it is possible to have the representation reversed, e.g., fs(3=3/16)!  

Is this more useful?

**Comment by dwvanstone** [comment] 2016-04-13 23:12
> One other suggestion: it is possible to have the representation reversed, e.g., fs(3=3/16)! 

Yes, that would work, and it should be consistent with the swing dice:  t(25=Z)

Could it be a different symbol than "="? I kind of like left arrow:

left arrow
t(25&larr;Z)  fs(3&larr;3/16)!

**Comment by blackshadowshade** [comment] 2016-04-13 23:17
There is another, totally different way of addressing this problem which was discussed briefly a long time ago. What about replacing the circles that are currently the background of the die value with an image that more closely corresponds to the number of sides that a die has?

e.g., a 4-sider would have a triangle behind it, a 6-sider would have a square behind it, a 20-sider would have the top of an icosahedron

That way, there's an extra visual cue as to how many sides there are, and we're not changing the recipe representation at all.

**Comment by Hurtay** [comment] 2016-04-14 07:01
> What about replacing the circles that are currently the background of the die value with an image that more closely corresponds to the number of sides that a die has?

Any chance to see a sample how this would look like?

**Comment by irilyth** [comment] 2016-04-14 11:19
Hmm, I feel like I've seen a mockup somewhere, but I don't remember where, and thirty seconds of searching didn't turn it up.

I think that'd be a fine idea too; I'd probably still be in favor of adding bold, but would like to see it.

**Comment by cgolubi1** [comment] 2016-04-14 11:33
One worry i've always had about changing the shape is that it might increase the incidence of the number being totally off-center in the die.  We might be able to test for this, but it's something that i think does happen in some browsers some of the time now (it looks great in *my* browser), and i think if we had more shapes, it might happen more.  Not a blocker, just a consideration.

**Comment by blackshadowshade** [comment] 2016-04-14 22:44
What about I work with @Hurtay on the new backgrounds for the BotM? I think that I could get a reasonable concept of how the backgrounds would change, and @Hurtay would be able to create the background images reasonably quickly. Then, we'd be able to give you a mockup of a number of die sizes.

**Comment by Hurtay** [comment] 2016-04-15 06:59
I'm not quite sure if I can do this but I'll try my best.

**Comment by blackshadowshade** [comment] 2016-04-18 15:32
So, to let you know what's happened on this:

@Hurtay has generated a number of simple images, which I'll use as templates to design the required CSS when I get to changing the background images.

I've refactored the code that displays the die table so that any change to the die background becomes a simple change that is isolated to a small function, instead of requiring changes to a monolith function.

Once the refactoring has been accepted, the actual change of background will be pretty simple, with most of the work being the correct design of the CSS to match the background image templates.

**Comment by irilyth** [comment] 2016-04-18 15:41
Cool cool. Do we also want to do the boldface business meanwhile, or nah? I think it'd be worthwhile, but don't feel strongly about it.

**Comment by Hurtay** [comment] 2016-04-19 07:19
I think the bold numbers were an improvement. But before deciding what to do and what to leave out I'd still prefer to see a preview of the dice-shapes in the regular playmat. If that's possible.

**Comment by blackshadowshade** [comment] 2016-04-25 06:59
![die_images_1](https://cloud.githubusercontent.com/assets/2898401/14776036/bc95b3e2-0b06-11e6-9a66-4e04f9078cf9.png)

I'm attaching a first cut for comment. Obviously, we'll need the die images to be backed with either white or grey, depending on whether the dice are active or not, but that's not a problem. Also, the lines on the dice could be greyer, so that they don't conflict with the die value so much. Everything about the actual die images is up for negotiation if people want us to pursue this images of die image backgrounds.

**Comment by Hurtay** [comment] 2016-04-25 10:58
I agree about the lines being still too dominant. I'll dot them or lighten them up or something.
And providing you with white/grey backgrounds shouldn't be a problem either.

But we'll probably need another shape for d8/d10? It looks a bit strange to me now to see a d12 when it should be a d8. We should at least have shapes of the real existing, regular sizes. Or what do you think?

In general I think it easier now to see at one quick glance what size the swing dice is. And maybe combine it with the bold lettering from the version 3 weeks ago?

**Comment by blackshadowshade** [comment] 2016-04-25 11:02
Sure, we'll eventually need the correct images for the standard die sizes.

I've been thinking about the bolding, and I think that it makes things rather busy (for me, distracting). Then again, I've never had trouble with die sizes of swing or option dice.

**Comment by blackshadowshade** [comment] 2016-04-25 11:08
Also, my thought is that the d12 should have 10 outer sides, to match what you see on a real d12 from the top.

**Comment by AdmiralJota** [comment] 2016-04-25 13:19
It appears that, at the moment, the 7-, 8-, 10-, and 12-sided dice all use the same symbol, as do the 2- and 4-sided dice. Is the plan to ultimately have a different symbol for every size we support, or do we expect some of them to look them same? If the latter, I'm not sure that it really helps address the problem that this ticket is for.

**Comment by blackshadowshade** [comment] 2016-04-25 13:28
The initial issue was distinguishing a 1- and an 8-sider, or a 4- and a 10-sider.

The plan would be to have images for up to 2, 4, 6, 8, 10, 12, 20, 30, and 100 sides.

**Comment by AdmiralJota** [comment] 2016-04-25 13:42
Also, how do we intend to handle twin dice?

**Comment by blackshadowshade** [comment] 2016-04-25 13:49
I'm happy to discuss suggestions for this after we decide if we want to do the die backgrounds or not.  :)

**Comment by irilyth** [comment] 2016-04-25 13:56
I like the die backgrounds.

**Comment by dwvanstone** [comment] 2016-04-25 20:01
I also think the die backgrounds are pretty and add character to the site. Mr. irilyth, will this solve the original issue that you expressed?

**Comment by Hurtay** [comment] 2016-04-25 22:08
Here is a new draft - not actually coded, just the shapes of the dice copied into the picture above. The size might vary a bit because of that.
I've changed the shapes completely to have them look more like real dice. I've tried a second version with dotted lines inside the dice but I'm afraid they look quite bland so I'm just presenting the nicer one for now.
/Users/Ute/Desktop/BM/in Arbeit/background dice/playmat1.png
I'm not sure how to do a d2 or d100, they both are just a circle, aren't they? One is a coin and the other a ball.

**Comment by blackshadowshade** [comment] 2016-04-25 22:54
The d2 is a plain 2D circle, in my mind---or perhaps a coin, with a little bit of the edge showing. The d100 should be more like a golf ball, so there should be some sort of 3-D texture on it, unlike the d2.

I'm not sure about the particular angle on the 3D objects in the image above, but what you have is certainly a good starting point. The only one that doesn't look obvious for me is the d10.

**Comment by AdmiralJota** [comment] 2016-04-26 00:26
While a d2 is a circle due to being a coin, a d1 is a circle for being a marble.

**Comment by blackshadowshade** [comment] 2016-04-26 00:42
And a d0 is a circle due to being a zero?  XD

**Comment by blackshadowshade** [comment] 2016-04-30 02:14
Here's a screenshot using updated backgrounds (currently without a circle for d2 or smaller).

![die_backgrounds](https://cloud.githubusercontent.com/assets/2898401/14933282/d8bb4c52-0ecc-11e6-9d26-839c5c6c6ebe.png)

I'm not totally convinced by the slightly off-centre look of the dice. I think that I'd rather a little more symmetry when it's possible.

**Comment by Hurtay** [comment] 2016-05-01 12:48
Personally I thought especially the off-center look is better than a pure geometrical symmetry, it looks more realistic this way. But if you all agree I'll go back to symmetry more like last weekend's version.

**Comment by irilyth** [comment] 2016-05-01 12:54
I don't have a strong feeling either way. I like that the asymmetry might make it easier to distinguish the different types that look otherwise similar; but I do think the symmetry looks a little cleaner, although it might just be the gray lines vs the white shapes, not sure.

If it'd be easy to have two apples-to-apples alternatives to compare, that'd be cool. If that's a pain, I think either is probably fine.

**Comment by cgolubi1** [comment] 2016-05-02 01:24
I'd vote for the symmetrical version, i just think it looks nicer.  Regardless, it's great that folks are putting so much energy into working on this!

**Comment by cgolubi1** [comment] 2016-05-06 12:07
One thought i have about this is: i bet it wouldn't be hard for "die shape set" to be a player option, and i think we should treat it that way from the start.  Then we can offer three options: symmetric, realistic, and circles (i.e. the status quo), and add more later if people come up with other shape sets they want.

**Comment by irilyth** [comment] 2016-05-06 13:26
I like user preferences, so if this one wouldn't make testing too awful, that sounds fine to me!

**Comment by blackshadowshade** [comment] 2016-05-06 21:47
Considering that I've broken this feature up into two parts (the refactoring, and the actual addition of the feature), I think that this should be quite reasonable to test, since the actual code changes to implement the feature will still be manageable.

**Comment by Hurtay** [comment] 2016-05-07 20:49
Have both versions and the original circles as preferences for every player to choose from is a brilliant idea!
I'm working at the symmetric shapes again right now. I thought it would probably be better to have them all look a bit alike, i.e. either all have lines inside or none. So the later version would be just plain outlines. What do you prefer? I'll start with the pure outlines right now. We need every shape in white (active), grey (inactive) and black (taken), right?
And for the realistic versions I've dotted the lines so they are less prominent than what we've seen above.
I'll send them to bss later today so maybe he can create irilyth's symmetric apples vs realistic apples game for us to compare them and decide about having or not having inner lines and if the shapes are good enough to use.

**Comment by blackshadowshade** [comment] 2016-05-07 23:29
Yes, that's all correct. I'll get some screenshots up as soon as I can after I receive the images.

**Comment by Hurtay** [comment] 2016-05-08 01:24
I just sent you 81 image files for 8 dice-sizes: realistic and symmetric shapes, with complete, dotted and completely without inner lines, in white, black and grey. It might be quite chaotic to get these all into the right place...
And even when we want to give players to choose from realistic and symmetric shapes we first would still have to decide how we prefer them to be concerning inner lines.

**Comment by blackshadowshade** [comment] 2016-05-08 05:54
Many thanks. I'll work on this tonight and get some screenshots up for you all.

**Comment by blackshadowshade** [comment] 2016-05-09 13:07
And here we go, screenshots as promised.

Circles:
![bm_circles_grey](https://cloud.githubusercontent.com/assets/2898401/15113955/bf02cd2e-163a-11e6-9e53-c6c7e8a0056c.png)
![bm_circles_white](https://cloud.githubusercontent.com/assets/2898401/15113956/bf087062-163a-11e6-818c-08a6f5610130.png)

Realistic:
![bm_realistic_grey](https://cloud.githubusercontent.com/assets/2898401/15113957/bf1215a4-163a-11e6-97e6-a4c6ee164e3a.png)
![bm_realistic_white](https://cloud.githubusercontent.com/assets/2898401/15113958/bf1db3a0-163a-11e6-9ecc-1d2d64ae29a3.png)

Symmetric:
![bm_symmetric_grey](https://cloud.githubusercontent.com/assets/2898401/15113960/bf286480-163a-11e6-9ffb-81f8451e2582.png)
![bm_symmetric_white](https://cloud.githubusercontent.com/assets/2898401/15113961/bf3e78b0-163a-11e6-9bfd-82d2b7dddf9a.png)

**Comment by Hurtay** [comment] 2016-05-09 13:17
Am I vain when I say I like it? Actually I like both, symmetric and realistic.
Only you took a d20 image for the d12 dice, didn't you?

**Comment by dwvanstone** [comment] 2016-05-09 13:22
The realistic images disturb my sense of symmetry. They make me feel slightly agitated. I usually don't have a lot of time to parse an image and I find the realistic ones take me more time. 

I love the symmetric ones.

**Comment by blackshadowshade** [comment] 2016-05-09 13:32
Ah, good point on the d12. I'd left it out of the logic. That's an easy fix (and I would have picked it up with the unit tests that I'm writing now).

**Comment by blackshadowshade** [comment] 2016-05-09 13:39
And here are the corrected screenshots with the correct d12 images:

![bm_realistic_grey](https://cloud.githubusercontent.com/assets/2898401/15114839/44b4342c-163f-11e6-9163-582a75052c43.png)
![bm_realistic_white](https://cloud.githubusercontent.com/assets/2898401/15114842/4510a00e-163f-11e6-8943-243b512f062d.png)
![bm_symmetric_grey](https://cloud.githubusercontent.com/assets/2898401/15114841/450e0466-163f-11e6-8bba-4a03a89d2b4d.png)
![bm_symmetric_white](https://cloud.githubusercontent.com/assets/2898401/15114840/450b6cb0-163f-11e6-80b8-8070fd9e1ddb.png)

**Comment by blackshadowshade** [comment] 2016-05-09 13:44
So, here are my subjective impressions about these images:
- the realistic and symmetric d20 images are slightly off-centre
- the symmetric d10 image doesn't immediately say "10-sided die" to me
- the realistic d12 image works for me in white and grey, but the black version doesn't immediately say "12-sided die" to me

**Comment by Hurtay** [comment] 2016-05-10 05:04
To summarize what you've said: you are not convinced of the realistic shapes in general. So maybe let's stick with the symmetic shapes and forget about the realistic ones.

off-center:
Even the circle you gave me as a template to start with is off-center so how can the others not be? It's the value numbers being off-center, not the symmetric shapes, believe me. 
If you prefer I could try to get the shapes off-center, too, to go better with the off-center numbers.

d10: 
The problem is that if you look at a d10 from the side it looks very much like a d8. Just the inner lines are different. You hardly see the different angle. That's why I went for a view from slightly above, so the shape is unique.
I can change that of course but I'd prefer if you have a suggestion of how to change it.

inner lines:
I made the inner lines less prominent because in a previous draft you said they would conflict with the values if they are as they were. But this was about the realistic shapes. So I only created the dotted inner lines in the symmetric shapes.
Ok, we can go back to more dominant lines in the symmetric shapes. Maybe it will be easier then to immediately recognize d10 and d12.

I won't be able to come up with new drafts before probably May 21st. So it's enough time to decide what exactly I should change.

**Comment by blackshadowshade** [comment] 2016-05-10 05:19
@AdmiralJota, you've traditionally been our go-to person on UI design decisions. What do you think about the images?

**Comment by cgolubi1** [comment] 2016-05-10 12:12
So my issue with the symmetric d10 image is that it has six sides (as in, the outline of the visible shape is six-sided), whereas the d12 image has five sides.  One thing we're trying to accomplish here is to give players more hints as to which dice are their big dice, to help reduce frustration caused by wrong play caused by misreading dice.

Given that, i think i might want not so much symmetric as geometric, where it's strictly the case that dice with more logical sides, have a shape whose outline has more sides.

**Comment by Hurtay** [comment] 2016-05-10 12:24
So you'd prefer the d10 to look very similar to the d8? Since the sizes of these two are quite similar, too, it makes sense. 
Then we'd have

- d1,d2 - 0 sides (circle)
- d3,d4 - 3 sides (triangle)
- d5,d6 - 4 sides (square)
- d7,d8 - 4 sides (kite)
- d9,d10 - 4 sides (kite)
- d11,d12 - 5 sides (pentagon)
- d13-d20 - 6 sides (hexagon)
- d21-d30 - many sides (can't remember)

This follows your logic of amount of outer lines increases = amount of sizes increases.

**Comment by cgolubi1** [comment] 2016-05-10 12:44
Yep, that sounds right to me.

**Comment by AdmiralJota** [comment] 2016-05-10 23:36
I think I'd like to see how the d10 looks as an asymmetric pentagon as well -- symmetric horizontally, but distorted vertically. As if you were looking down on the die, but with the point aimed toward you.

**Comment by Hurtay** [comment] 2016-05-11 16:03
Be my guest to draw one. :)
I'll go for the symmetric, slightly flat kite shape.

**Comment by AdmiralJota** [comment] 2016-05-11 18:57
Alas, I am no artist, and I am sure that this looks terrible:

![d10](https://cloud.githubusercontent.com/assets/5848173/15192756/9a54f0ac-1788-11e6-9136-c748ccf4fb73.png)

But this is vaguely the sort of idea I had in mind.

**Comment by Hurtay** [comment] 2016-05-11 19:01
Interesting. You look at the d10 from above.
Hm, I probably could do that. But I'm afraid it might look quite similar to the d12 that way.
What do you prefer?

**Comment by Hurtay** [comment] 2016-05-12 05:57
Sorry, I thought this button was for closing the draft of a comment.
My bad.

**Comment by blackshadowshade** [comment] 2016-05-14 12:17
So, I'm working on the user-preference, and I've come across the question of which background should be the default. What do you all think? Circles, symmetric, or realistic?

**Comment by AdmiralJota** [comment] 2016-05-15 14:19
This sounds like something we might want to poll the community on once all three options are available on the site.

**Comment by Hurtay** [comment] 2016-05-15 19:42
I'd suggest to leave the circles as default for now.
To ask the community when they have had the chance to see and try the shapes sounds right.
What about the subject of the numbers being off-center? Does it bother anyone?

**Comment by blackshadowshade** [comment] 2016-05-28 11:46
For interest, here's what the symmetric images looks like now.

![spooky_prudence](https://cloud.githubusercontent.com/assets/2898401/15627127/8cf3ec4a-251d-11e6-994f-56b11ad3bc7e.png)

**Comment by blackshadowshade** [comment] 2016-05-28 12:53
I'm removing the BotM label from this because I've put in loads of work and there are two pull requests up to solve it.

**Closed** 2016-07-10 00:12 UTC
Labels: enhancement, fix submitted, newbie, UI
