### ISSUE TITLE
Players seeing blank screens when interacting with site

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2377] opened 2018-07-03 14:55 UTC
One player, Patches, wanted to interact with the Forums but couldn't. (And couldn't post the bug there.) I offered to post his bug report here.

> It basically happens in three situations: whenever I try to get to forums in any way (i.e. through "Forum" or "New post"" links, even when using the http of forum a trying to get there directly), when I try to access Open games or when I click "Go to your next pending game", when there's no more of those. Browser window goes all white and as far as I know nothing gets loaded ever. I noticed some slowdown in the rest of the website, too, and have to wait for page to load for up to five or so seconds, but in those cases at least that line between upper menu and rest of the page appears and I know the rest of the page will follow shortly. But in case of forum, open games and jump to monitor through next pending game not even the line appears. I'm using Firefox 60.0.2 (64-bit version) on Ubuntu 16.04 (64-bit distro).

 

Probably related to #1989 , but with no error message appearing. I've seen this error myself, but reloading the page usually clears it up.

**Comment by AdmiralJota** [comment] 2018-07-03 15:50
My guess is that it's the caching issue that we have after a new release. It might be Issue #2288?

If I'm right, until the problem gets fixed, they'll need to do a hard refresh (control-F5 in Windows) when it happens to load the page without caching.

**Comment by Patches1984** [comment] 2018-07-03 16:26
Great, Ctrl+F5 seems to be working alright even on Ubuntu, thanks!
(Also, now I know about this outside forum so won't need to bother others about my bugs - thanks to devious for assistance!)

**Comment by blackshadowshade** [comment] 2018-07-03 16:59
Yeah, this is certainly a duplicate of #2288. We're aware of it, but Chaos hasn't gotten around to testing a number of possible workarounds yet.

Closing as a duplicate.

**Closed by blackshadowshade** 2018-07-03 16:59 UTC
Labels: duplicate
