### ISSUE TITLE
Feedback on vacation feature for 2016-05 release

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#1983] opened 2016-04-27 13:42 UTC
Fix things related to the new vacation feature that need to be done by the May release.

**Comment by irilyth** [comment] 2016-04-27 13:42
This should probably mostly be blockers; mark "nice to have but not blocker" suggestions as such.

**Comment by irilyth** [comment] 2016-04-27 13:43
It might be good to have more help text on the preferences page -- like "enter a message to let folks know you're away from the game, leave blank otherwise" or something. In particular, clarifying that it's text to enter if you're away (as opposed to your daydreams about where you'd like to go on vacation, or whatever), and that you should just leave the box blank if you're not away.

**Comment by irilyth** [comment] 2016-04-27 13:44
Also to clarify that it's fine to put text there whenever you're more away from the game than usual for a little while -- busy at work, solo parenting, actually on vacation, etc.

**Comment by blackshadowshade** [comment] 2016-04-27 14:06
I'm currently getting the following error:

"Argument (vacation_message) to function savePlayerInfo is invalid"

when setting the vacation message to the following (between the lines)

-----
I am currently on a [b]Zen[/b] holiday: the holiday that you're on when you're not on holiday.

我我不是中国人.

הַלְלוּיָהּ | הַלְלוּ אֶת יְהֹוָה מִן הַשָּׁמַיִם הַלְלוּהוּ בַּמְּרוֹמִ

I am still on a [b]Zen[/b] holiday: the holiday that you're on when you're not on holiday.

More
-----

I presume that we have a character counting / Unicode size issue here.

**Comment by dwvanstone** [comment] 2016-04-27 14:12
Does the same error happen on the other text boxes, such as "Comment" or "Homepage" or "Real Name"?

**Comment by blackshadowshade** [comment] 2016-04-27 14:20
No, there's no error when putting it in the Comment box. The accepted text is simply truncated on save.

**Comment by blackshadowshade** [comment] 2016-04-27 14:26
If you want another test case, you could use this:

-----
אהַלְלוּיָהּ | הַלְלוּ אֶת יְהֹוָה מִן הַשָּׁמַיִם הַלְלוּהוּ בַּמְּרוֹמִים:
בהַלְלוּהוּ כָּל מַלְאָכָיו הַלְלוּהוּ כָּל צְבָאָיו (כתיב צְבָאָו) :
גהַלְלוּהוּ שֶׁמֶשׁ וְיָרֵחַ הַלְלוּהוּ כָּל כּוֹכְבֵי אוֹר:
דהַלְלוּהוּ שְׁמֵי הַשָּׁמָיִם וְהַמַּיִם אֲשֶׁר | מֵעַל הַשָּׁמָיִם:
היְהַלְלוּ אֶת שֵׁם יְהֹוָה כִּי הוּא צִוָּה וְנִבְרָאוּ:
ווַיַּעֲמִידֵם לָעַד לְעוֹלָם חָק נָתַן וְלֹא יַעֲבוֹר:
זהַלְלוּ אֶת יְהֹוָה מִן הָאָרֶץ תַּנִּינִים וְכָל תְּהֹמוֹת:
חאֵשׁ וּבָרָד שֶׁלֶג וְקִיטוֹר רוּחַ סְעָרָה עֹשָׂה דְבָרוֹ:
טהֶהָרִים וְכָל גְּבָעוֹת עֵץ פְּרִי וְכָל אֲרָזִים:
יהַחַיָּה וְכָל בְּהֵמָה רֶמֶשׂ וְצִפּוֹר כָּנָף:
יאמַלְכֵי אֶרֶץ וְכָל לְּאֻמִּים שָֹרִים וְכָל שֹׁפְטֵי אָרֶץ:
יבבַּחוּרִים וְגַם בְּתוּלוֹת זְקֵנִים עִם נְעָרִים:
יגיְהַלְלוּ | אֶת שֵׁם יְהֹוָה כִּי נִשְׂגָּב שְׁמוֹ לְבַדּוֹ הוֹדוֹ עַל אֶרֶץ וְשָׁמָיִם:
ידוַיָּרֶם קֶרֶן | לְעַמּוֹ תְּהִלָּה לְכָל חֲסִידָיו לִבְנֵי יִשְׂרָאֵל עַם קְרֹבוֹ הַלְלוּיָהּ:
-----

which gets truncated in the Comment field to 

אהַלְלוּיָהּ | הַלְלוּ אֶת יְהֹוָה מִן הַשָּׁמַיִם הַלְלוּהוּ בַּמְּרוֹמִים:
בהַלְלוּהוּ כָּל מַלְאָכָיו הַלְלוּהוּ כָּל צְבָאָיו (כתיב צ

**Comment by dwvanstone** [comment] 2016-04-27 14:31
I'm having a hard time repeating the bug -- I can copy and paste any of that text into my vacation message box (Firefox 38.7) and it gets successfully truncated and saved. Which browser are you using? Does the error appear in a log somewhere or on your screen?

**Comment by blackshadowshade** [comment] 2016-04-27 14:34
I'm using Safari 9.1 on my Mac, and the error appears at the top of my screen (just above "Profile Settings"). Let me try it on Firefox.

**Comment by blackshadowshade** [comment] 2016-04-27 14:36
The truncation works correctly in Firefox 45.0.2 on Mac.

**Comment by dwvanstone** [comment] 2016-04-27 14:42
I'll see if I can spot a difference as to how Comments and Vacation Messages are stored. They should be the same. I can also try using Safari on a Mac at home at some point.

**Comment by blackshadowshade** [comment] 2016-04-27 14:59
Just to be clear, I don't see this as a blocker for the release, but it needs to be tidied up, even if we customise the error message to something more like "Message too long".

**Comment by cgolubi1** [comment] 2016-05-02 00:33
Hmm, okay.  There hasn't been any followup on this in the past four days.  Do we know anything more about this bug?  Has anyone found any blockers?

**Comment by blackshadowshade** [comment] 2016-05-02 00:49
My suspicion is that there's some issue with the number of characters allocated, or the amount of space allocated in the database.

**Comment by cgolubi1** [comment] 2016-05-02 00:53
Nah, it has nothing to do with the database --- the error you're seeing is being thrown by ApiSpec, you're not getting to the database.  I'm looking into it now.

**Comment by cgolubi1** [comment] 2016-05-02 01:16
Okay, so: shadowshade, i'll argue that this can't be a blocker because the game description field works exactly the same way --- if you submit a long Hebrew game description in Firefox, you get a game with a truncated game description.  If you submit a long Hebrew game description in Safari, you get an exception.

The issue is that, for vacation_message (as for game description), ApiSpec.php imposes a maximum message length.  For comment, there's no maximum message length, so in the case of comment, the database insert is what's doing the truncating.

Furthermore, for whatever reason, Firefox is truncating the string somewhat (identically in both the comment and vacation_message cases afaict) before passing it to the backend, so in the Firefox case, the vacation_message passes ApiSpec's filter (but afaict ApiSpec's filter is *still* longer than what the DB will accept, so the DB still truncates further).  In the Safari case, there's no (less?) truncation, so the vacation_message fails ApiSpec.

We should get to the bottom of this and make our string parsing more consistent.  But i suspect that if we throw vacation_message over the fence as is, we'll get the same number of complaints about the unicode length limit that we've gotten about game descriptions, which is none.

**Comment by Hurtay** [comment] 2016-05-02 08:54
So far I didn't encounter any problems. I used long and short messages - even emoticons - and everything worked fine for me. But I didn't try chinese or other non-latin fonts as the game is all in English anyway.
> But i suspect that if we throw vacation_message over the fence as is, we'll get the same number of complaints about the unicode length limit that we've gotten about game descriptions, which is none.
I hope that will be true.

**Comment by AdmiralJota** [comment] 2016-05-02 13:19
I didn't get any problems either, but I was testing in Firefox.

**Comment by cgolubi1** [comment] 2016-07-10 00:34
It'd be great if we could close this one out; anyone willing to poke through the comments and see what needs to be spun off into other issues?

**Comment by dwvanstone** [comment] 2016-07-10 12:35
I can try to do this at some point, but not today.

**Comment by cgolubi1** [comment] 2016-07-10 12:37
> I can try to do this at some point, but not today.

Thanks!  Assigning it to you, and no rush.

**Comment by blackshadowshade** [comment] 2021-07-07 14:20
Closing this one because I've heard no complaints about the vacation feature.

**Closed by blackshadowshade** 2021-07-07 14:20 UTC
Labels: UI, bug
