### ISSUE TITLE
Clicking Monitor from a rejected game returns you to the same screen.

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1734] opened 2015-10-09 04:32 UTC
I created http://dev.buttonweavers.com/ui/game.html?game=1880 as a test of rejecting, and asked my opponent to reject it.  They did, and that much seems to work. When I got to it (by clicking Next Game from a different game) I got this screen:

![screen shot 2015-10-09 at 12 28 44 am](https://cloud.githubusercontent.com/assets/6092544/10385845/dfc0e2c4-6e1c-11e5-8f2d-a9c4f8d4d738.jpg)

But it doesn't offer a Next Game button from this screen, even though there are other games where it's currently my turn. Worse, when I click "Monitor" it briefly goes to http://dev.buttonweavers.com/ui/index.html?mode=monitor but then immediately back to the same screen.

**Comment by blackshadowshade** [comment] 2015-10-09 04:34
What does the Next Game link from the top do?

**Comment by jimmosk** [comment] 2015-10-09 04:42
Doh, there's a Next Game in the header. I literally never noticed that (because redundancy means never having to look to see if there's redundancy...).  That one works fine.
Still, for those of us used to having a "Go to your next pending game (at least N)" link in the body of the page, could I request it appear on this Rejected Game screen?

**Comment by blackshadowshade** [comment] 2015-10-09 04:44
You can request it, but I'd suggest rather under #1731. I'll then close this issue.

**Comment by blackshadowshade** [comment] 2015-10-09 04:44
Note to self: check what the Monitor button actually does.  :)

**Comment by jimmosk** [comment] 2015-10-09 04:48
Done!

**Comment by jimmosk** [comment] 2015-10-09 04:51
Might it be a problem not with how Monitor works, but how it's decided which games still need to be shown to the player? Seeing the Rejected screen once ought to remove it from the Still In Play category...

**Comment by blackshadowshade** [comment] 2015-10-09 04:52
I'm marking this as wontfix for the moment, because I think that the issue will become invisible once we actually have #1731 up and running. However, I agree that it's a bug, and I'll take a look at the Monitor link when I can.

**Comment by irilyth** [comment] 2015-10-09 14:38
I ran into this just now, and it might be the same situation, but wanted to be sure: I clicked on my bookmark for the dev site, which is http://dev.buttonweavers.com/ui/index.html?mode=preference, and that brought me to http://dev.buttonweavers.com/ui/game.html?game=1881, which says "This game has been rejected." What's weird about that is that I don't think I created or rejected any games on the dev site yet... What is game 1881, and why is it popping up here for me, and how can I make it go away? I don't see it on the overview at all...

**Comment by blackshadowshade** [comment] 2015-10-09 15:09
It's possible to see more details about the game by looking at the Javascript that is sent over, e.g., by using Firebug. That shows:

{"data":{"gameId":1881,"gameState":"REJECTED","activePlayerIdx":null,"playerWithInitiativeIdx":null,"roundNumber"
:1,"maxWins":3,"description":"LENGTHY DESCRIPTION DESCRIBING WHY TO JOIN!","previousGameId":null,"validAttackTypeArray"
:[],"gameSkillsInfo":[],"playerDataArray":[{"playerId":25,"button":{"name":"Ngozi","recipe":"(4) (6)
 (8) (10) (X)","artFilename":"ngozi.png"},"activeDieArray":[],"capturedDieArray":[],"outOfPlayDieArray"
:[],"swingRequestArray":[],"optRequestArray":[],"prevSwingValueArray":[],"prevOptValueArray":[],"waitingOnAction"
:false,"roundScore":0,"sideScore":0,"gameScoreArray":{"W":0,"L":0,"D":0},"lastActionTime":1444318570
,"hasDismissedGame":false,"canStillWin":true,"playerName":"Devious","playerColor":"#cccccc"},{"playerId"
:2,"button":{"name":"Eiko","recipe":"(4) (6) (6) (12) (X)","artFilename":"eiko.png"},"activeDieArray"
:[],"capturedDieArray":[],"outOfPlayDieArray":[],"swingRequestArray":[],"optRequestArray":[],"prevSwingValueArray"
:[],"prevOptValueArray":[],"waitingOnAction":true,"roundScore":0,"sideScore":0,"gameScoreArray":{"W"
:0,"L":0,"D":0},"lastActionTime":1444317687,"hasDismissedGame":false,"canStillWin":true,"playerName"
:"irilyth","playerColor":"#dddddd"}],"currentPlayerIdx":false,"gameActionLog":[],"gameActionLogCount"
:0,"gameChatLog":[],"gameChatLogCount":0,"timestamp":1444318570,"gameChatEditable":false},"message":"Loaded
 data for game 1881.","status":"ok"}

That tells me that it's Devious vs irilyth, meaning that you must have selected to join the game and then rejected it?

**Comment by irilyth** [comment] 2015-10-09 15:13
Nope, I'm pretty sure I never rejected the game. Maybe devious did? That seems fine, the creator should be able to say "oops never mind", but I think that shouldn't impinge on the other player at all.

Right now, this game is always the first thing that the Monitor jumps to, but it doesn't show up anywhere that I can dismiss it.

**Comment by blackshadowshade** [comment] 2015-10-09 15:15
If you hit Overview then Monitor, does it still try to go to this game?

**Comment by dwvanstone** [comment] 2015-10-09 15:19
I probably rejected that game. (Sorry!)

**Comment by blackshadowshade** [comment] 2015-10-09 15:19
No, that's fine. That's part of the testing that we wanted!

**Comment by irilyth** [comment] 2015-10-09 15:20
> If you hit Overview then Monitor, does it still try to go to this game?

Yep. If I hit Next Game, it goes on to the next one, just like any other game I might skip. I moved in my other games, and when the last one said "Go to your next pending game (at least 1)", it went back to the overview page in Monitor mode, as usual. After 1 minute, it reloaded, and went back to 1881 again.

It seems to behave exactly like a game where some action is required of me. Which I guess some was, when devious created the game; maybe when he rejected it, the bit that says "it's my turn to act" wasn't cleared?

**Comment by blackshadowshade** [comment] 2015-10-09 15:22
Okay, I'll get a fix in for this as soon as I've worked out what's going on. I might also do a bit of database tweaking to fix your dev experience in the short term, but that won't be for the next day or so (until I've worked out what the problem is).

**Comment by irilyth** [comment] 2015-10-09 15:23
I don't mind my dev experience right now, no sweat about that.

**Comment by blackshadowshade** [comment] 2015-10-09 15:29
I note that for irilyth in game 1881, we still have: "waitingOnAction" set to true. That's probably why the game keeps popping up in your Monitor.

Of course, the true problem is that the Monitor shouldn't be showing anything that has been rejected anyway. I'm guessing that it's a one-line fix in the database query that the Monitor uses.

**Comment by cgolubi1** [comment] 2015-10-29 01:45
Trying to reproduce this bug to test the fix, and having trouble doing so.

**Comment by cgolubi1** [comment] 2015-10-29 01:48
Oh, i see -- if the player who created the game rejects it, you wind up in that state.  Yeah, okay, got it.  That works.

**Closed** 2015-10-29 01:52 UTC
Labels: backend, bug, fix submitted
