### ISSUE TITLE
Indicate the Slowness of Slow dice

### ISSUE THREAD

**Issue by jimmosk** [buttonmen-dev/buttonmen#1653] opened 2015-07-09 18:13 UTC
I'm in a game on the main site involving Giant. I had forgotten about its slowness, and was confused when it didn't get initiative. Could there be more of an indication somewhere, to make up for the fact that we decided not to label its individual dice with the w skill?  It'd be useful to know both when creating a game, and when playing it.

**Comment by dwvanstone** [comment] 2015-07-09 19:15
Are there any other buttons currently implemented that have a button-specific (as opposed to die-specific) power? At minimum this should be in the button's description, but would we want text under the button that specifies what the power is? (For Flying Squirrel, Japanese Beetle, etc.) Or even just a link "*SPECIAL BUTTON POWER*" that goes to the description page for the button?

**Comment by blackshadowshade** [comment] 2015-07-09 23:36
I'm going to suggest that this is a duplicate of #1200 and close this. However, if there's something I've missed, feel free to reopen this.

**Closed by blackshadowshade** 2015-07-09 23:36 UTC
