### ISSUE TITLE
RandomBMMixed doesn't show up in list of button specials until game has been accepted

### ISSUE THREAD

**Issue by cgolubi1** [buttonmen-dev/buttonmen#1851] opened 2015-12-11 12:58 UTC
What it says on the tin.  I'll annotate with a few screencaps.

I'm pretty confident this is an API/backend bug.

**Comment by cgolubi1** [comment] 2015-12-11 12:59
A new game on the dev site, with TFS and RandomBMMixed.  TFS shows up in the skill list, RandomBMMixed doesn't:
![on_dev_site](https://cloud.githubusercontent.com/assets/2898207/11744305/2848e8ec-9fdd-11e5-9849-3f6d65a69fde.png)

**Comment by cgolubi1** [comment] 2015-12-11 13:02
A new game using the code in #1799, and the same game when active, demonstrating that RandomBMMixed (in addition to the skills introduced by RandomBMMixed) shows up once the game becomes active:

New:
![on_virtualbox_new](https://cloud.githubusercontent.com/assets/2898207/11744346/88b48e98-9fdd-11e5-9873-b9cb170ab2fc.png)

Active:
![on_virtualbox_active](https://cloud.githubusercontent.com/assets/2898207/11744348/924b66f2-9fdd-11e5-8ec2-326c9bddc451.png)

**Comment by cgolubi1** [comment] 2015-12-11 13:04
* This affects all RandomBM types, not just mixed (i.e. it also affects Vanilla, which has no skills)
* This has nothing to do with whether there's a second button with a button special (i.e. Avis vs RandomBM* has the same issue)

**Comment by blackshadowshade** [comment] 2015-12-14 13:11
Duplicate of #1775.

**Closed** 2015-12-14 13:11 UTC
Labels: backend, bug, duplicate
