### ISSUE TITLE
Forum links in game chat include too much text

### ISSUE THREAD

**Issue by irilyth** [buttonmen-dev/buttonmen#2390] opened 2018-08-15 12:10 UTC
In http://www.buttonweavers.com/ui/game.html?game=40894, I put a forum link into a game chat message, and it made the rest of my message into the text of the link, looking like this:

![bm](https://user-images.githubusercontent.com/4923138/44147567-a156cba4-a062-11e8-92ef-549fccc66c65.png)

The text I had entered in the chat box was:

> Forum reminder delivery service! Mad Robin 21 is starting up; see [forum=636,13132] for details, and send me some picks?

**Comment by blackshadowshade** [comment] 2018-08-15 13:38
Okay, this appears to be by design. You need a closing tag, namely [/forum].

> Forum reminder delivery service! Mad Robin 21 is starting up; see [forum=636,13132]link_text[/forum] for details, and send me some picks?

should work.

**Comment by blackshadowshade** [comment] 2018-08-15 13:40
It leaves the question open as to whether we should support a link with no text better than we currently do.

**Comment by blackshadowshade** [comment] 2018-08-15 23:59
I'll leave this issue open for discussion for a couple of days, and we'll see what people think.

**Comment by blackshadowshade** [comment] 2018-10-12 13:03
Closing this issue then.

**Closed by blackshadowshade** 2018-10-12 13:03 UTC
Labels: wontfix
