### ISSUE TITLE
Echo v. Japanese Beetle: power not copied

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#1730] opened 2015-10-05 18:56 UTC
I'm playing a TJB vs. Echo game (#1861 on the dev site) and I (as TJB) was able to make a skill attack against Echo. I don't think I should be able to...unless Echo only copies the dice and not the power of the button itself.

**Comment by blackshadowshade** [comment] 2015-10-05 21:05
This is expected behaviour. Echo only copies the recipe, but not any button special.

**Comment by blackshadowshade** [comment] 2015-10-05 21:07
Do you think that we need to update the description of Echo, which is currently:
"Copies the opponent's button recipe."

**Comment by irilyth** [comment] 2015-10-05 21:17
Hmm, are Echo and Zero *supposed* to copy button specials? I thought that they would.

#372 says "Zero assumes all stats and Iconic abilities of her opponent (same as Echo)", which might imply that both Zero and Echo would copy button specials, or maybe only that Zero copies the special abilities of other Tenchi Muyo buttons.

http://www.beatpeopleup.com/brom.html talks about this somewhat, but isn't conclusive. It says that there are issues in a Giant vs Giant match (because neither can win initiative), and also "The only reason to restrict Giant and Echo is that they cannot meet each other.", but most of the other text talks about Giant vs Giant and Echo vs Echo, not Giant vs Echo. And it also says "Her entire recipe is dictated by her special ability. Also, since the text dictates that only her "basic recipe" matches that of her opponent" which makes it sound like it's only the "basic recipe" that's copied, and not button special abilities, hmm.

I think it's more fun if Echo (and Zero) copy button specials, and I think that they did on the old site, although I don't remember for sure.

**Comment by blackshadowshade** [comment] 2015-10-05 22:05
Okay, I'll open this up to anyone who is interested then. Do we want to have Echo and Zero copy only basic recipes or be a perfect clone of the opponent's button?

I can see "it's more fun" arguments both ways. How do you see it?

**Comment by blackshadowshade** [comment] 2015-10-05 22:10
One analogue from Pokemon would be Ditto, who copies the appearance and moves of its opponent. However, it doesn't change its inherent neutral type, which means that it is generally slightly less powerful because its type doesn't match the type of its moves.

**Comment by dwvanstone** [comment] 2015-10-06 11:12
Would you want to have the best of both worlds and have Echo copy the basic recipe and Zero be a perfect clone? (I mean, why have two identical buttons?) An "Echo", by name, implies it's not as good as the original!

**Comment by irilyth** [comment] 2015-10-06 13:21
That's an interesting idea, I'd be fine with having Echo and Zero be different in this respect.

**Comment by jimmosk** [comment] 2015-10-06 21:26
I like that idea, though honestly I'm not sure why if "Echo" implies it isn't as good, that "Zero" doesn't imply it's much worse!
I do think that that necessitates changes to both buttons' descriptions. I'd make Echo's read:
"Copies the opponent's button recipe, though not any special powers unique to that button (like The Japanese Beetle's immunity to skill attacks)".

And on Zero's I'd remove "(same as Echo)".

**Comment by irilyth** [comment] 2015-10-06 21:40
The official text of Echo's button special is printed on the button, so maybe include that as the description, with a parenthetical clarifying that it doesn't copy other button special abilities?

**Comment by blackshadowshade** [comment] 2023-03-14 01:02
I'm going to close this issue, in favour of #2017.

**Closed by blackshadowshade** 2023-03-14 01:02 UTC
Labels: question
