### ISSUE TITLE
Add fancy autocomplete drop-down for button names when joining Open Game

### ISSUE THREAD

**Issue by dwvanstone** [buttonmen-dev/buttonmen#2402] opened 2018-10-01 14:12 UTC
If a player joins an Open Game where their button wasn't previously selected, they get a "Choose Button" dropdown. It would be nice if this, too, had an autocomplete list to help them choose a button.

**Comment by blackshadowshade** [comment] 2020-11-11 23:45
Duplicate of #993.

**Closed** 2020-11-11 23:45 UTC
Labels: duplicate
